# This docker-compose just exists for testing purpose in a development environment
version: "3.8"

x-env: &env ${ENV:-development}
x-redis-host: &redis-host ${REDIS_HOST:-redis}

x-network: &network
  networks:
    - service

services:
  service:
    container_name: service
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config:/root/config
    ports:
      - 6066:6066
    <<: *network

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./docs.Dockerfile
    ports:
      - 8085:8085
    <<: *network

  # asynq related services
  redis:
    image: redis:4
    container_name: *redis-host
    ports:
      - 6379:6379
    volumes:
      - redis:/redis-data/data
    <<: *network

  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    command: asynqmon --redis_addr=redis:6379
    environment:
      - redis_addr=redis:6379
    ports:
      - 8080:8080
    <<: *network

  # Kafka related services
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    <<: *network
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.1.182
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "emails:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    <<: *network

  # NATS related services
  nats1:
    image: nats:2.8
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    volumes:
      - nats:/data/nats-server/jetstream
    <<: *network
  nats2:
    image: nats:2.8
    container_name: nats2
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    volumes:
      - nats1:/data/nats-server/jetstream
    depends_on: ["nats1"]
    <<: *network
  nats3:
    image: nats:2.8
    container_name: nats3
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    volumes:
      - nats2:/data/nats-server/jetstream
    depends_on: ["nats1"]    
    <<: *network

volumes:
  redis:
  nats:
  nats1:
  nats2:

networks:
  service:
